name: Maven Build

on: workflow_dispatch
#  pull_request:
#  push:
#    branches:
#      - master

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean install
          mvn -pl solutions blueprinter:blueprint@readme

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README.md
